name: Day23 workflow
on: push
jobs:
build:
run-on: ubuntu-latest
steps:
-name: Checkout Repository
uses: actions/checkout@v4
-name: Print Welcome message
run: echo "Welcome Sweety to github actions"
-name: Show current Directory
run: pwd
-name: Print completion message
run: echo "Workflow completed successfully"
