name: Day29 AWS Deployment Pipeline


on:
   push:


jobs:
   deploy-to-aws:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Build Docker  Image
        run: docker build -t sweety-devops-project .


      - name: Show Docker Images
        run: docker image


      - name: Simulate AWS EC2 Deployment
        run: echo "Deploying Docker container to AWS EC2..."


      - name: Simulate Container Start
        run: echo "Starting container on AWS server..."


      - name: Deployment Successful
        run: echo "Application deployed successfully to AWS EC2..."
